#!/bin/bash -e
# (export VERSION=0.0.15; git reset --hard HEAD^; git tag -d v${VERSION}; git push origin :v${VERSION}; git push -f)
prefix=experiment

if [ ! -e ${prefix}-versions.json ]
then
  echo "no ${prefix}-versions.json found"
  exit 1
fi

if git status|grep modified
then
  echo "please commit changes first"
  exit 1
fi

test -n "${WEB_EXT_API_KEY:?"please set WEB_EXT_API_KEY"}"
test -n "${WEB_EXT_API_SECRET:?"please set WEB_EXT_API_SECRET"}"
test -n "${GITHUB_TOKEN:?please set GITHUB_TOKEN env var}"

current_version=$(cat manifest.json |jq -r ".version")
next_patch_version=$(( $(echo ${current_version}|sed "s/${prefix}-//g"|sed -E "s/([0-9]+)\.([0-9]+)\.([0-9]+)/\3/") + 1 ))
next_version=${prefix}-$(echo ${current_version}|sed -E "s/${prefix}-([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2.${next_patch_version}/")

read -p "current version is ${current_version} ... next version (${next_version}): " next_version_user
next_version=${next_version_user:-${next_version}}

# bump version in manifest.json
sed -i "" -e "s/: \"${current_version}\"/: \"${next_version}\"/" manifest.json

# add new release to versions.json
jq ".addons.\"{cad4f60e-e46e-4d66-8c11-e09194d4df7d}\".updates += [{\"version\":\"${next_version}\", \"update_link\": \"https://github.com/kesselborn/conex/releases/download/v${next_version}/conex-${next_version}-an.fx.xpi\"}]" ${prefix}-versions.json > ${prefix}-next_versions.json
mv ${prefix}-next_versions.json ${prefix}-versions.json

# commit version bumps and create new tag
git commit -m "Bump to version ${next_version}" manifest.json ${prefix}-versions.json
git tag v${next_version}

# create signed addon
web-ext sign --api-key ${WEB_EXT_API_KEY:?"please set WEB_EXT_API_KEY"} \
             --api-secret ${WEB_EXT_API_SECRET:?"please set WEB_EXT_API_SECRET"} \
             --ignore-files tags tabgroups-backup.json tabgroups-backup-small.json web-ext-artifacts *.xpi icons/*.afdesign release versions.json || true

{ git push --tags && git push; } || true

################ github release upload
AUTH="Authorization: token ${GITHUB_TOKEN:?please set GITHUB_TOKEN env var}"
VERSION=v${next_version}
LOCAL_ASSET=web-ext-artifacts/conex-${next_version}-an+fx.xpi

repo=$(git remote get-url origin|cut -d: -f2|sed 's/\.git$//g')

release_notes_file=$(mktemp /tmp/release_notes.XXXXXX)
echo "release notes for github:" > ${release_notes_file}
vi ${release_notes_file} || true
release_notes=$(cat ${release_notes_file} | while read l; do echo -n "$l\\n"; done)
release_body="{\"tag_name\":\"${VERSION}\",\"name\":\"${VERSION}\",\"body\":\"${release_notes}\",\"draft\":false,\"prerelease\":false}"
rm -f ${release_notes_file}

response=$(set -x; curl -ifL -H"Accept: application/vnd.github.v3+json" -H"${AUTH}" -XPOST -d "${release_body}" https://api.github.com/repos/${repo}/releases) \
  || { echo "Error: does the release already exist? Check https://github.com/${repo}/releases/tag/${VERSION}"; exit 1; }

upload_url=$(echo ${response}|sed -E 's/.*"upload_url": "([^"]+)".*/\1/g'|cut -d{ -f1)

echo "Uploading asset... $LOCAL_ASSET" >&2

curl -L# --data-binary @"${LOCAL_ASSET}" \
         -H "Content-Type: application/x-xpinstall" \
         -H"Accept: application/vnd.github.v3+json" -H"${AUTH}" \
         -XPOST ${upload_url}?name=$(basename $LOCAL_ASSET)

cat<<EOF


Successfully created release -- edit edit release notes at: https://github.com/${repo}/releases/edit/${VERSION}


EOF

read -p "release to mozilla as well (y/n)?" -n1 answer
test "${answer}" == "y" || exit 0

echo "release notes:"
echo "${release_notes}"

# remove github update url from manifest
cat manifest.json | jq 'del(.applications.gecko.update_url)' > next_manifest.json
mv next_manifest.json manifest.json
################ github release upload end

web-ext sign --id '{ec9d70ea-0229-49c0-bbf7-0df9bbccde35}' --api-key ${WEB_EXT_API_KEY:?'please set WEB_EXT_API_KEY'} --api-secret ${WEB_EXT_API_SECRET:?'please set WEB_EXT_API_SECRET'} --ignore-files tags tabgroups-backup.json tabgroups-backup-small.json web-ext-artifacts *.xpi icons/*.afdesign release versions.json || true

git checkout manifest.json

cat<<EOF

Edit https://addons.mozilla.org/en-us/developers/addon/conex/versions

Diff: https://github.com/kesselborn/conex/compare/v${current_version}...${VERSION}

EOF
