#!/bin/bash -e
# (export VERSION=0.0.15; git reset --hard HEAD^; git tag -d v${VERSION}; git push origin :v${VERSION}; git push -f)

if git status|grep modified
then
  echo "please commit changes first"
  exit 1
fi

test -n "${WEB_EXT_API_KEY:?"please set WEB_EXT_API_KEY"}"
test -n "${WEB_EXT_API_SECRET:?"please set WEB_EXT_API_SECRET"}"
test -n "${GITHUB_TOKEN:?please set GITHUB_TOKEN env var}"

current_version=$(cat manifest.json |jq -r ".version")
next_patch_version=$(( $(echo ${current_version}|sed -E "s/([0-9]+)\.([0-9]+)\.([0-9]+)/\3/") + 1 ))
next_version=$(echo ${current_version}|sed -E "s/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2.${next_patch_version}/")
printf "current version is %s  ... next version (%s): " ${current_version} ${next_version}

read next_version_user
if [ -n "${next_version_user}" ]
then
  next_version=${next_version_user}
fi

echo "${next_version}"

sed -i "" -e "s/: \"${current_version}\"/: \"${next_version}\"/" manifest.json
git commit -m "Bump to version ${next_version}" manifest.json
git tag v${next_version}

web-ext sign --api-key ${WEB_EXT_API_KEY:?"please set WEB_EXT_API_KEY"} \
             --api-secret ${WEB_EXT_API_SECRET:?"please set WEB_EXT_API_SECRET"} \
             --ignore-files tags tabgroups-backup.json tabgroups-backup-small.json web-ext-artifacts *.xpi release || true

{ git push --tags && git push; } || true

################ github release upload
AUTH="Authorization: token ${GITHUB_TOKEN:?please set GITHUB_TOKEN env var}"
VERSION=v${next_version}
LOCAL_ASSET=web-ext-artifacts/taborama-${next_version}-an+fx.xpi

repo=$(git remote get-url origin|cut -d: -f2|sed 's/\.git$//g')
release_body="{\"tag_name\":\"${VERSION}\",\"name\":\"${VERSION}\",\"body\":\"...\",\"draft\":false,\"prerelease\":false}"

response=$(set -x; curl -ifL -H"Accept: application/vnd.github.v3+json" -H"${AUTH}" -XPOST -d "${release_body}" https://api.github.com/repos/${repo}/releases) \
  || { echo "Error: does the release already exist? Check https://github.com/${repo}/releases/tag/${VERSION}"; exit 1; }

upload_url=$(echo ${response}|sed -E 's/.*"upload_url": "([^"]+)".*/\1/g'|cut -d{ -f1)

echo "Uploading asset... $LOCAL_ASSET" >&2

curl -L# --data-binary @"${LOCAL_ASSET}" \
         -H "Content-Type: application/x-xpinstall" \
         -H"Accept: application/vnd.github.v3+json" -H"${AUTH}" \
         -XPOST ${upload_url}?name=$(basename $LOCAL_ASSET)

cat<<EOF


Successfully created release -- edit edit release notes at: https://github.com/${repo}/releases/edit/${VERSION}


EOF
################ github release upload end

cat<<EOF
Submit it to listed mozilla:

echo "call: web-ext sign --id '{ec9d70ea-0229-49c0-bbf7-0df9bbccde35}' --api-key ${WEB_EXT_API_KEY:?'please set WEB_EXT_API_KEY'} --api-secret ${WEB_EXT_API_SECRET:?'please set WEB_EXT_API_SECRET'} --ignore-files tags tabgroups-backup.json tabgroups-backup-small.json web-ext-artifacts *.xpi release"

Edit https://addons.mozilla.org/en-us/developers/addon/taborama/versions

Diff: https://github.com/kesselborn/taborama/compare/v${current_version}...${VERSION}

EOF
